version: '3'
services:
  kafka:
    image: apache/kafka:latest
    container_name: app_kafka
    restart: always
    ports:
      - "9092:9092"

  database:
    image: postgres
    container_name: app_postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8088:8080"
volumes:
  db_data: