spring:
  application:
    name: homework_kafka_consumer
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
#metricsListener:
#  concurrency: 2

server:
  port: 28088